# Generated by Django 6.0.6 on 2026-06-10 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationIA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "historique_messages",
                    models.JSONField(
                        default=list, verbose_name="Historique des messages"
                    ),
                ),
                (
                    "nb_requetes_aujourd_hui",
                    models.IntegerField(
                        default=0, verbose_name="Nombre de requêtes aujourd'hui"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_ia",
                        to="accounts.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation IA",
                "verbose_name_plural": "Conversations IA",
                "ordering": ["-timestamp"],
            },
        ),
    ]
