# Generated by Django 6.0.6 on 2026-07-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationia",
            name="tokens_entree_total",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tokens entrée (cumulé)"
            ),
        ),
        migrations.AddField(
            model_name="conversationia",
            name="tokens_sortie_total",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Tokens sortie (cumulé)"
            ),
        ),
    ]
