# Generated by Django 6.0.6 on 2026-07-17 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_client_cle_api_ia_personnelle"),
        ("ai_assistant", "0002_conversationia_tokens_entree_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationia",
            name="titre",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Titre du fil"
            ),
        ),
        migrations.AlterField(
            model_name="conversationia",
            name="nb_requetes_aujourd_hui",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="conversationia",
            name="timestamp",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière activité du fil"
            ),
        ),
        migrations.AlterField(
            model_name="conversationia",
            name="tokens_entree_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="conversationia",
            name="tokens_sortie_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="QuotaIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nb_requetes_aujourd_hui",
                    models.IntegerField(
                        default=0, verbose_name="Nombre de requêtes aujourd'hui"
                    ),
                ),
                (
                    "tokens_entree_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tokens entrée (cumulé)"
                    ),
                ),
                (
                    "tokens_sortie_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tokens sortie (cumulé)"
                    ),
                ),
                ("derniere_maj", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota_ia",
                        to="accounts.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quota IA",
                "verbose_name_plural": "Quotas IA",
            },
        ),
    ]
