# Generated by Django 6.0.6 on 2026-07-17 14:47

from django.db import migrations


def migrer_vers_quotaia(apps, schema_editor):
    """Copie le quota/tokens (jusqu'ici sur l'unique ConversationIA de chaque client)
    vers une ligne QuotaIA par client, avant que ces champs ne soient retirés de
    ConversationIA (migration suivante). À ce stade, chaque client n'a encore qu'UN
    seul fil (la fonctionnalité multi-fils n'existe pas encore) : on prend donc
    simplement les valeurs de ce fil unique."""
    ConversationIA = apps.get_model('ai_assistant', 'ConversationIA')
    QuotaIA = apps.get_model('ai_assistant', 'QuotaIA')
    for conv in ConversationIA.objects.all():
        QuotaIA.objects.update_or_create(
            client_id=conv.client_id,
            defaults={
                'nb_requetes_aujourd_hui': conv.nb_requetes_aujourd_hui,
                'tokens_entree_total': conv.tokens_entree_total,
                'tokens_sortie_total': conv.tokens_sortie_total,
            },
        )


def revenir_en_arriere(apps, schema_editor):
    """Pas de retour en arrière automatique : les données QuotaIA restent en place
    (retirer la migration suivante suffit à re-remplir ConversationIA à zéro)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0003_add_quotaia_and_titre"),
    ]

    operations = [
        migrations.RunPython(migrer_vers_quotaia, revenir_en_arriere),
    ]
