# Generated by Django 6.0.6 on 2026-07-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0004_migrer_quotas_vers_quotaia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationia",
            name="nb_requetes_aujourd_hui",
        ),
        migrations.RemoveField(
            model_name="conversationia",
            name="tokens_entree_total",
        ),
        migrations.RemoveField(
            model_name="conversationia",
            name="tokens_sortie_total",
        ),
    ]
