# Generated by Django 6.0.6 on 2026-07-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0005_retirer_quota_de_conversationia"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConversationIA",
        ),
    ]
