# Generated by Django 5.2.10 on 2026-07-17 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_client_cle_api_ia_personnelle"),
        ("ai_assistant", "0006_supprimer_conversationia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(blank=True, default="", max_length=200)),
                ("messages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_ia",
                        to="accounts.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation IA",
                "verbose_name_plural": "Conversations IA",
                "ordering": ["-updated_at"],
            },
        ),
    ]
