# Generated by Django 6.0.6 on 2026-06-10 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "moisConcerné",
                    models.CharField(
                        max_length=50, verbose_name="Mois concerné (ex: Mai 2026)"
                    ),
                ),
                (
                    "consomméeEstimée_kWh",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Consommation estimée (kWh)",
                    ),
                ),
                (
                    "montantEstimé_FCFA",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Montant estimé (FCFA)",
                    ),
                ),
                (
                    "écartSurMoisPrécédent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Écart sur mois précédent (%)",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previsions",
                        to="accounts.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prévision de Facturation",
                "verbose_name_plural": "Prévisions de Facturation",
                "ordering": ["-moisConcerné"],
            },
        ),
    ]
