# Generated by Django 6.0.6 on 2026-06-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prevision",
            options={
                "ordering": ["-annee_mois", "-moisConcerné"],
                "verbose_name": "Prévision de Facturation",
                "verbose_name_plural": "Prévisions de Facturation",
            },
        ),
        migrations.AddField(
            model_name="prevision",
            name="annee_mois",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=7,
                verbose_name="Mois (AAAA-MM)",
            ),
        ),
    ]
