# Generated by Django 5.2.10 on 2026-07-18 02:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_client_cle_api_ia_personnelle"),
        ("analytics", "0002_alter_prevision_options_prevision_annee_mois"),
    ]

    operations = [
        migrations.CreateModel(
            name="RechargeCredit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "montant_FCFA",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Montant rechargé (FCFA)",
                    ),
                ),
                ("dateRecharge", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recharges_credit",
                        to="accounts.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recharge de crédit prépayé",
                "verbose_name_plural": "Recharges de crédit prépayé",
                "ordering": ["-dateRecharge"],
            },
        ),
    ]
