"""
Django settings for aoceda project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-default-secret-key-aoceda')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "daphne",               # serveur ASGI (WebSocket de l'appel Live) : remplace runserver, DOIT être 1er
    "jazzmin",              # thème admin, DOIT être avant django.contrib.admin
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",  # blackliste les refresh tokens après rotation
    "channels",             # WebSocket (appel Live de l'assistant IA)

    # AOCEDA Apps
    "apps.accounts.apps.AccountsConfig",
    "apps.sensors.apps.SensorsConfig",
    "apps.analytics.apps.AnalyticsConfig",
    "apps.alerts.apps.AlertsConfig",
    "apps.dashboard.apps.DashboardConfig",
    "apps.ai_assistant.apps.AiAssistantConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "aoceda.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "aoceda.wsgi.application"
# ASGI : HTTP + WebSocket (appel Live de l'assistant). Avec « daphne » dans INSTALLED_APPS,
# `manage.py runserver` sert directement cette application.
ASGI_APPLICATION = "aoceda.asgi.application"


# Database — PostgreSQL en production, SQLite en dev local (DB_ENGINE=sqlite3)
_DB_ENGINE = config('DB_ENGINE', default='postgresql')

if _DB_ENGINE == 'sqlite3':
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config('DB_NAME', default='aoceda'),
            "USER": config('DB_USER', default='aoceda'),
            "PASSWORD": config('DB_PASSWORD', default=''),
            "HOST": config('DB_HOST', default='localhost'),
            "PORT": config('DB_PORT', default='5432'),
            "OPTIONS": {
                "client_encoding": "UTF8",
            },
            "TEST": {
                "NAME": "test_aoceda",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Africa/Abidjan"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Custom Auth Model
AUTH_USER_MODEL = 'accounts.Utilisateur'

# Après une connexion Django (site d'admin), rediriger vers le dashboard admin.
# (Le login CLIENT utilise un flux JS/JWT séparé, non concerné par ce réglage.)
LOGIN_REDIRECT_URL = '/admin/'

# ─────────────────────────────────────────────────────────────────────────────
# Assistant IA (chatbot AOCEDA) — clés et réglages lus dans le .env (modèle sans
# valeurs : .env.example). Mêmes noms que D:\AOCEDA_CHATBOT\.env (CLES_API.txt,
# partie « À COPIER ») : le bloc s'y colle tel quel. Une clé absente désactive
# le service concerné proprement, jamais de plantage.
# ─────────────────────────────────────────────────────────────────────────────
AI_PROVIDER    = config('AI_PROVIDER', default='deepseek')        # cerveau partagé : 'deepseek' ou 'grok'
AI_DAILY_LIMIT = config('AI_DAILY_LIMIT', default=0, cast=int)    # questions / jour / client ; 0 = illimité
AI_HISTORIQUE_RETENTION_JOURS = config('AI_HISTORIQUE_RETENTION_JOURS', default=7, cast=int)

# DeepSeek : le cerveau du chat écrit et vocal
DEEPSEEK_API_KEY     = config('DEEPSEEK_API_KEY', default='')
DEEPSEEK_API_URL     = config('DEEPSEEK_API_URL', default='https://api.deepseek.com/chat/completions')
DEEPSEEK_MODEL       = config('DEEPSEEK_MODEL', default='deepseek-chat')
DEEPSEEK_TIMEOUT     = config('DEEPSEEK_TIMEOUT', default=30, cast=int)
DEEPSEEK_MAX_TOKENS  = config('DEEPSEEK_MAX_TOKENS', default=800, cast=int)
DEEPSEEK_TEMPERATURE = config('DEEPSEEK_TEMPERATURE', default=0.3, cast=float)   # 0,3 : chiffres réels restitués fidèlement

# Gemini : l'appel Live, compte 1 (GEMINI_API_KEY) puis comptes de réserve _2 à _9
GEMINI_API_KEY   = config('GEMINI_API_KEY', default='')
GEMINI_CLES_LIVE = [GEMINI_API_KEY] + [config(f'GEMINI_API_KEY_{i}', default='') for i in range(2, 10)]
GEMINI_MODEL     = config('GEMINI_MODEL', default='gemini-2.5-flash')
GEMINI_API_URL   = config('GEMINI_API_URL', default='https://generativelanguage.googleapis.com/v1beta/models')
GEMINI_TIMEOUT     = config('GEMINI_TIMEOUT', default=30, cast=int)
GEMINI_MAX_TOKENS  = config('GEMINI_MAX_TOKENS', default=800, cast=int)
GEMINI_TEMPERATURE = config('GEMINI_TEMPERATURE', default=0.3, cast=float)

# Clé IA personnelle d'un client (ancien assistant, retirée à l'étape 5 de l'intégration)
OPENAI_API_URL     = config('OPENAI_API_URL', default='https://api.openai.com/v1/chat/completions')
OPENAI_MODEL       = config('OPENAI_MODEL', default='gpt-4o-mini')
OPENAI_TIMEOUT     = config('OPENAI_TIMEOUT', default=30, cast=int)
OPENAI_MAX_TOKENS  = config('OPENAI_MAX_TOKENS', default=800, cast=int)
OPENAI_TEMPERATURE = config('OPENAI_TEMPERATURE', default=0.3, cast=float)
ANTHROPIC_API_URL     = config('ANTHROPIC_API_URL', default='https://api.anthropic.com/v1/messages')
ANTHROPIC_MODEL       = config('ANTHROPIC_MODEL', default='claude-haiku-5-5')
ANTHROPIC_TIMEOUT     = config('ANTHROPIC_TIMEOUT', default=30, cast=int)
ANTHROPIC_MAX_TOKENS  = config('ANTHROPIC_MAX_TOKENS', default=800, cast=int)
ANTHROPIC_TEMPERATURE = config('ANTHROPIC_TEMPERATURE', default=0.3, cast=float)

# Cerebrium : la voix baoulé sur carte graphique (GPU)
CEREBRIUM_PROJECT   = config('CEREBRIUM_PROJECT', default='')
CEREBRIUM_API_KEY   = config('CEREBRIUM_API_KEY', default='')
CEREBRIUM_SERVICE_ACCOUNT_TOKEN = config('CEREBRIUM_SERVICE_ACCOUNT_TOKEN', default='')
# Hugging Face (téléchargement des modèles), OpenRouter (secours de l'agent Live),
# NiuTrans (2e traducteur du baoulé, facultatif)
HF_TOKEN             = config('HF_TOKEN', default='')
OPENROUTER_KEY_AGENT = config('OPENROUTER_KEY_AGENT', default='')
NIUTRANS_API_KEY     = config('NIUTRANS_API_KEY', default='')

# Modèles locaux et données de l'assistant. Les modèles pèsent ~6 Go : sur ce PC ils
# restent sur D: (chemins dans le .env) ; sans eux, le dioula / baoulé / la voix de
# secours se désactivent proprement.
CHATBOT_MODELES_DIR = Path(config('CHATBOT_MODELES_DIR', default=str(BASE_DIR / 'donnees_ia' / 'modeles')))
CHATBOT_HF_HOME     = Path(config('CHATBOT_HF_HOME', default=str(BASE_DIR / 'donnees_ia' / 'hf')))         # Whisper
CHATBOT_KOKORO_DIR  = Path(config('CHATBOT_KOKORO_DIR', default=str(BASE_DIR / 'donnees_ia' / 'kokoro')))  # voix de secours
CHATBOT_DONNEES_DIR = Path(config('CHATBOT_DONNEES_DIR', default=str(BASE_DIR / 'donnees_ia' / 'donnees')))  # cache voix, journaux, réserves Live
CHATBOT_PYTHON_OMNIVOICE = config('CHATBOT_PYTHON_OMNIVOICE', default='')   # voix baoulé sur ce PC (secours du GPU)
CHATBOT_PORT_OMNIVOICE   = config('CHATBOT_PORT_OMNIVOICE', default=8771, cast=int)

# Réglages facultatifs de l'assistant (valeurs par défaut = celles du chatbot validé)
CHATBOT_WHISPER          = config('CHATBOT_WHISPER', default='small')        # small = précis (~4 s), base = rapide
CHATBOT_MODELES_LIVE     = [m.strip() for m in config('CHATBOT_MODELES_LIVE', default='').split(',') if m.strip()]
CHATBOT_GPU_MINUTES_JOUR = config('CHATBOT_GPU_MINUTES_JOUR', default=120, cast=int)  # plafond GPU / jour (≈ 2 $)
CHATBOT_VOIX_BAOULE_GPU  = config('CHATBOT_VOIX_BAOULE_GPU', default=True, cast=bool)
CHATBOT_VOIX_BAOULE      = config('CHATBOT_VOIX_BAOULE', default=True, cast=bool)
CHATBOT_BAOULE_CHAINE    = config('CHATBOT_BAOULE_CHAINE', default=True, cast=bool)
CHATBOT_ONNX_RESERVE     = config('CHATBOT_ONNX_RESERVE', default='retrecir')  # mémoire des oreilles dioula / baoulé

# ─────────────────────────────────────────────────────────────────────────────
# Assistant IA — xAI Grok (API compatible OpenAI), si AI_PROVIDER=grok
# ─────────────────────────────────────────────────────────────────────────────
GROK_API_KEY     = config('GROK_API_KEY', default='')
GROK_MODEL       = config('GROK_MODEL', default='grok-4.3')
GROK_API_URL     = config('GROK_API_URL', default='https://api.x.ai/v1/chat/completions')
GROK_TIMEOUT     = config('GROK_TIMEOUT', default=30, cast=int)        # secondes
GROK_MAX_TOKENS  = config('GROK_MAX_TOKENS', default=800, cast=int)    # borne la réponse (coût/latence)
GROK_TEMPERATURE = config('GROK_TEMPERATURE', default=0.3, cast=float)

# ─────────────────────────────────────────────────────────────────────────────
# Assistant IA — Dioula STT (Meta MMS, ONNX quantifié, optionnel)
# Si le dossier n'existe pas, le module se désactive proprement (mode fallback).
# ─────────────────────────────────────────────────────────────────────────────
AI_DIOULA_STT_MODEL_DIR = BASE_DIR / config('AI_DIOULA_STT_MODEL_DIR', default='brain/dioula_stt')

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # JWT + révocation immédiate des jetons émis avant un changement de mot de passe
        # (apps/accounts/authentication.py ; réglage perdu lors de la sauvegarde « teleport »)
        'apps.accounts.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Pagination : page_size 1000 évite toute coupure pour le démo tout en
    # rendant les réponses listes conformes {count, next, previous, results}.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 1000,
    # Rate limiting (mémoire §4.3.2).
    # - scope 'mesures' = 100 req/min : appliqué UNIQUEMENT aux POST d'ingestion
    #   ESP32 (MesureEnergieView.post, ZMCTIngestionView.post) via ScopedRateThrottle.
    # - 'user' = garde anti-abus large : la navigation de l'espace client déclenche
    #   une rafale d'appels par page (summary, facture, previsions, sensors, alertes,
    #   serie, repartition, users/me…). Un plafond à 100/min étranglait toute
    #   l'interface (429 en cascade → l'UI croyait le compte déconnecté). 2000/min
    #   ne se déclenche jamais en usage humain normal mais bloque un vrai abus.
    # Le quota assistant IA (10 req/jour) est géré dans apps.ai_assistant.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'user': '2000/min',
        'mesures': '100/min',
    },
}

# JWT Token configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,  # un ancien refresh est invalidé dès qu'il est rafraîchi
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Token d'authentification pour le pont série Arduino (serial_bridge.py)
ARDUINO_BRIDGE_TOKEN = config('ARDUINO_BRIDGE_TOKEN', default='')

# ---------------------------------------------------------------------------
# Envoi d'e-mails (SMTP) — alertes d'énergie, réinitialisation de mot de passe, etc.
# (mémoire §6.4.2). Le BACKEND est choisi automatiquement :
#   • EMAIL_HOST renseigné dans .env  → SMTP réel (les e-mails partent vraiment) ;
#   • EMAIL_HOST vide (dev)           → CONSOLE (les e-mails s'affichent dans le terminal).
# On peut toujours forcer via EMAIL_BACKEND dans .env.
# ---------------------------------------------------------------------------
EMAIL_HOST          = config('EMAIL_HOST', default='')
EMAIL_PORT          = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER     = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS       = config('EMAIL_USE_TLS', default=True, cast=bool)    # port 587 (STARTTLS)
EMAIL_USE_SSL       = config('EMAIL_USE_SSL', default=False, cast=bool)   # port 465 (SSL direct)
if EMAIL_USE_SSL:
    EMAIL_USE_TLS = False   # Django interdit TLS et SSL simultanément
EMAIL_TIMEOUT       = config('EMAIL_TIMEOUT', default=15, cast=int)       # secondes, évite un blocage
DEFAULT_FROM_EMAIL  = config('DEFAULT_FROM_EMAIL', default='AOCEDA <no-reply@aoceda.ci>')
SERVER_EMAIL        = DEFAULT_FROM_EMAIL   # erreurs Django (500) vers cet expéditeur

EMAIL_BACKEND = config('EMAIL_BACKEND', default=(
    'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST
    else 'django.core.mail.backends.console.EmailBackend'))

# URL PUBLIQUE de base du site, pour les liens cliquables dans les e-mails
# (ex. lien de réinitialisation). En prod : https://ton-domaine.
FRONTEND_URL = config('FRONTEND_URL', default='http://127.0.0.1:8000').rstrip('/')

# ---------------------------------------------------------------------------
# Celery + Redis (mémoire §6.1.1), moteur d'anomalies planifié toutes les 5 min
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_TIMEZONE = TIME_ZONE

# ---------------------------------------------------------------------------
# Sécurité HTTP en production (mémoire §4.3.2), activée quand DEBUG=False
# ---------------------------------------------------------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# ---------------------------------------------------------------------------
# Jazzmin, thème du panneau d'administration Django
# ---------------------------------------------------------------------------
JAZZMIN_SETTINGS = {
    # ── Marque ────────────────────────────────────────────────────────────
    "site_title": "AOCEDA Admin",
    "site_header": "AOCEDA",
    "site_brand": "AOCEDA",
    "welcome_sign": "Bienvenue sur le panneau d'administration AOCEDA",
    "copyright": "AOCEDA, Monitoring Électrique Domestique · Côte d'Ivoire",

    # ── Icône de l'onglet ────────────────────────────────────────────────
    "site_icon": None,   # chemin vers un favicon dans STATIC si disponible
    "site_logo": None,   # logo dans la sidebar (laisser None = texte)

    # ── Navigation ───────────────────────────────────────────────────────
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Ordre + icônes des sections de la sidebar (FontAwesome 5)
    "order_with_respect_to": [
        "accounts", "sensors", "analytics", "alerts", "ai_assistant", "auth",
    ],
    "icons": {
        # Apps
        "accounts": "fas fa-users",
        "sensors": "fas fa-microchip",
        "analytics": "fas fa-chart-line",
        "alerts": "fas fa-bell",
        "ai_assistant": "fas fa-robot",
        "auth": "fas fa-lock",
        # Modèles
        "accounts.Utilisateur": "fas fa-user",
        "accounts.Client": "fas fa-user-circle",
        "accounts.Technicien": "fas fa-hard-hat",
        "accounts.Administrateur": "fas fa-user-shield",
        "sensors.Capteur": "fas fa-bolt",
        "sensors.Dispositif": "fas fa-wifi",
        "sensors.MesureEnergie": "fas fa-tachometer-alt",
        "sensors.Intervention": "fas fa-tools",
        "sensors.RapportIntervention": "fas fa-file-alt",
        "analytics.PrevisionFacturation": "fas fa-receipt",
        "alerts.Alerte": "fas fa-exclamation-triangle",
        "alerts.RegleDetection": "fas fa-sliders-h",
        "ai_assistant.ConversationIA": "fas fa-comments",
        "auth.Group": "fas fa-users-cog",
    },

    # ── Liens rapides en haut à droite ───────────────────────────────────
    "topmenu_links": [
        {"name": "Accueil site", "url": "/", "new_window": False,
         "icon": "fas fa-home"},
        {"name": "Dashboard client", "url": "/dashboard/", "new_window": False,
         "icon": "fas fa-tachometer-alt"},
        {"app": "sensors"},
    ],

    # ── Menu utilisateur connecté ─────────────────────────────────────────
    "usermenu_links": [
        {"name": "Site AOCEDA", "url": "/", "new_window": False,
         "icon": "fas fa-globe"},
    ],

    # ── Recherche ────────────────────────────────────────────────────────
    "search_model": ["accounts.Utilisateur", "accounts.Client", "sensors.Capteur"],

    # ── Divers ───────────────────────────────────────────────────────────
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": False,
    "show_ui_builder": False,
    "show_theme_chooser": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    # Thème par défaut : sombre AOCEDA
    "theme": "cyborg",                # Bootswatch le plus sombre (fond quasi-noir #060606)
    "default_theme_mode": "dark",     # data-bs-theme=dark au chargement
    "navbar": "navbar-dark",
    "navbar_fixed": True,
    "no_navbar_border": True,
    "brand_colour": "navbar-dark",
    "accent": "accent-warning",
    "sidebar": "sidebar-dark-warning",
    "sidebar_fixed": True,
    "sidebar_nav_child_indent": True,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
