"""
Django settings for aoceda project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-default-secret-key-aoceda')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])


# Application definition

INSTALLED_APPS = [
    "jazzmin",              # thème admin, DOIT être avant django.contrib.admin
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",  # blackliste les refresh tokens après rotation

    # AOCEDA Apps
    "apps.accounts.apps.AccountsConfig",
    "apps.sensors.apps.SensorsConfig",
    "apps.analytics.apps.AnalyticsConfig",
    "apps.alerts.apps.AlertsConfig",
    "apps.dashboard.apps.DashboardConfig",
    "apps.ai_assistant.apps.AiAssistantConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "aoceda.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "aoceda.wsgi.application"


# Database, PostgreSQL uniquement (pas de repli SQLite)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config('DB_NAME', default='aoceda'),
        "USER": config('DB_USER', default='aoceda'),
        "PASSWORD": config('DB_PASSWORD', default=''),
        "HOST": config('DB_HOST', default='localhost'),
        "PORT": config('DB_PORT', default='5432'),
        "OPTIONS": {
            "client_encoding": "UTF8",
        },
        "TEST": {
            "NAME": "test_aoceda",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Africa/Abidjan"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Custom Auth Model
AUTH_USER_MODEL = 'accounts.Utilisateur'

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Pagination : page_size 1000 évite toute coupure pour le démo tout en
    # rendant les réponses listes conformes {count, next, previous, results}.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 1000,
    # Rate limiting (mémoire §4.3.2) : 100 req/min pour les mesures ESP32.
    # Le quota assistant IA (10 req/jour) est géré dans apps.ai_assistant.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'user': '100/min',
    },
}

# JWT Token configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,  # un ancien refresh est invalidé dès qu'il est rafraîchi
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Token d'authentification pour le pont série Arduino (serial_bridge.py)
ARDUINO_BRIDGE_TOKEN = config('ARDUINO_BRIDGE_TOKEN', default='')

# ---------------------------------------------------------------------------
# Notifications email (mémoire §6.4.2), console en développement, SMTP en prod
# ---------------------------------------------------------------------------
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='alertes@aoceda.ci')

# ---------------------------------------------------------------------------
# Celery + Redis (mémoire §6.1.1), moteur d'anomalies planifié toutes les 5 min
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_TIMEZONE = TIME_ZONE

# ---------------------------------------------------------------------------
# Sécurité HTTP en production (mémoire §4.3.2), activée quand DEBUG=False
# ---------------------------------------------------------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# ---------------------------------------------------------------------------
# Jazzmin, thème du panneau d'administration Django
# ---------------------------------------------------------------------------
JAZZMIN_SETTINGS = {
    # ── Marque ────────────────────────────────────────────────────────────
    "site_title": "AOCEDA Admin",
    "site_header": "AOCEDA",
    "site_brand": "AOCEDA",
    "welcome_sign": "Bienvenue sur le panneau d'administration AOCEDA",
    "copyright": "AOCEDA, Monitoring Électrique Domestique · Côte d'Ivoire",

    # ── Icône de l'onglet ────────────────────────────────────────────────
    "site_icon": None,   # chemin vers un favicon dans STATIC si disponible
    "site_logo": None,   # logo dans la sidebar (laisser None = texte)

    # ── Navigation ───────────────────────────────────────────────────────
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Ordre + icônes des sections de la sidebar (FontAwesome 5)
    "order_with_respect_to": [
        "accounts", "sensors", "analytics", "alerts", "ai_assistant", "auth",
    ],
    "icons": {
        # Apps
        "accounts": "fas fa-users",
        "sensors": "fas fa-microchip",
        "analytics": "fas fa-chart-line",
        "alerts": "fas fa-bell",
        "ai_assistant": "fas fa-robot",
        "auth": "fas fa-lock",
        # Modèles
        "accounts.Utilisateur": "fas fa-user",
        "accounts.Client": "fas fa-user-circle",
        "accounts.Technicien": "fas fa-hard-hat",
        "accounts.Administrateur": "fas fa-user-shield",
        "sensors.Capteur": "fas fa-bolt",
        "sensors.Dispositif": "fas fa-wifi",
        "sensors.MesureEnergie": "fas fa-tachometer-alt",
        "sensors.Intervention": "fas fa-tools",
        "sensors.RapportIntervention": "fas fa-file-alt",
        "analytics.PrevisionFacturation": "fas fa-receipt",
        "alerts.Alerte": "fas fa-exclamation-triangle",
        "alerts.RegleDetection": "fas fa-sliders-h",
        "ai_assistant.ConversationIA": "fas fa-comments",
        "auth.Group": "fas fa-users-cog",
    },

    # ── Liens rapides en haut à droite ───────────────────────────────────
    "topmenu_links": [
        {"name": "Accueil site", "url": "/", "new_window": False,
         "icon": "fas fa-home"},
        {"name": "Dashboard client", "url": "/dashboard/", "new_window": False,
         "icon": "fas fa-tachometer-alt"},
        {"app": "sensors"},
    ],

    # ── Menu utilisateur connecté ─────────────────────────────────────────
    "usermenu_links": [
        {"name": "Site AOCEDA", "url": "/", "new_window": False,
         "icon": "fas fa-globe"},
    ],

    # ── Recherche ────────────────────────────────────────────────────────
    "search_model": ["accounts.Utilisateur", "accounts.Client", "sensors.Capteur"],

    # ── Divers ───────────────────────────────────────────────────────────
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": False,
    "show_ui_builder": False,
    "show_theme_chooser": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    # Thème par défaut : sombre AOCEDA
    "theme": "cyborg",                # Bootswatch le plus sombre (fond quasi-noir #060606)
    "default_theme_mode": "dark",     # data-bs-theme=dark au chargement
    "navbar": "navbar-dark",
    "navbar_fixed": True,
    "no_navbar_border": True,
    "brand_colour": "navbar-dark",
    "accent": "accent-warning",
    "sidebar": "sidebar-dark-warning",
    "sidebar_fixed": True,
    "sidebar_nav_child_indent": True,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
