# Generated by Django 6.0.6 on 2026-06-10 18:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse email"
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("technicien", "Technicien"),
                            ("admin", "Administrateur"),
                        ],
                        default="client",
                        max_length=50,
                    ),
                ),
                ("estActif", models.BooleanField(default=True)),
                ("token_reset", models.UUIDField(blank=True, null=True)),
                ("date_expiration_token", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "utilisateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "typeLogement",
                    models.CharField(
                        choices=[
                            ("Appartement", "Appartement"),
                            ("Villa", "Villa"),
                            ("Maison", "Maison"),
                        ],
                        default="Appartement",
                        max_length=50,
                    ),
                ),
                (
                    "tarifkWh_FCFA",
                    models.DecimalField(decimal_places=2, default=87.0, max_digits=10),
                ),
                ("adresse", models.TextField(blank=True, null=True)),
                ("numeroCIE", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
            bases=("accounts.utilisateur",),
        ),
        migrations.CreateModel(
            name="Technicien",
            fields=[
                (
                    "utilisateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("matricule", models.CharField(max_length=100, unique=True)),
                ("specialite", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "verbose_name": "Technicien",
                "verbose_name_plural": "Techniciens",
            },
            bases=("accounts.utilisateur",),
        ),
    ]
