# Generated by Django 6.0.6 on 2026-06-10 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrateur",
            fields=[
                (
                    "utilisateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "niveauAcces",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("super", "Super administrateur"),
                        ],
                        default="standard",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrateur",
                "verbose_name_plural": "Administrateurs",
            },
            bases=("accounts.utilisateur",),
        ),
    ]
