# Generated by Django 6.0.6 on 2026-06-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_administrateur"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="amperage",
            field=models.IntegerField(
                choices=[
                    (5, "5A (1,1 kW)"),
                    (10, "10A (2,2 kW)"),
                    (15, "15A (3,3 kW)"),
                ],
                default=10,
                verbose_name="Ampérage souscrit",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="typeCompteur",
            field=models.CharField(
                choices=[
                    ("postpaye", "Intelligent postpayé (facture mensuelle)"),
                    ("prepaye", "Prépayé (recharges)"),
                ],
                default="postpaye",
                max_length=20,
                verbose_name="Type de compteur",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="typeTarif",
            field=models.CharField(
                choices=[
                    ("social", "Domestique Social (5A uniquement)"),
                    ("general", "Domestique Général"),
                ],
                default="general",
                max_length=20,
                verbose_name="Type de tarif CIE",
            ),
        ),
    ]
