# Generated by Django 6.0.6 on 2026-06-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_client_amperage_client_typecompteur_client_typetarif"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="creditPrepaye_FCFA",
            field=models.DecimalField(
                decimal_places=2,
                default=15000.0,
                max_digits=12,
                verbose_name="Crédit prépayé rechargé (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="notifEmail",
            field=models.BooleanField(
                default=True, verbose_name="Notifications par e-mail"
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="telephone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Téléphone"
            ),
        ),
    ]
