# Generated by Django 6.0.6 on 2026-06-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_client_creditprepaye_fcfa_utilisateur_notifemail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="seuilCreditBas_FCFA",
            field=models.DecimalField(
                decimal_places=2,
                default=10000.0,
                max_digits=12,
                verbose_name="Seuil alerte crédit bas (FCFA)",
            ),
        ),
    ]
