# Generated by Django 6.0.6 on 2026-07-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_seuil_credit_bas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="creditPrepaye_FCFA",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Crédit prépayé rechargé (FCFA)",
            ),
        ),
    ]
