# Generated by Django 6.0.6 on 2026-07-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_client_creditprepaye_fcfa"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="nbPersonnesFoyer",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Nombre de personnes au foyer"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="superficie_m2",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Superficie du logement (m²)"
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                verbose_name="Photo de profil",
            ),
        ),
    ]
