# Generated by Django 5.2.10 on 2026-07-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_client_nbpersonnesfoyer_client_superficie_m2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False, verbose_name="A2F activée"),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="two_factor_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="two_factor_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
