# Generated by Django 5.2.10 on 2026-07-15 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs_client",
                to="accounts.client",
            ),
        ),
    ]
