# Generated by Django 6.0.6 on 2026-07-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_auditlog_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="absenceJusquau",
            field=models.DateField(
                blank=True, null=True, verbose_name="Absence jusqu'au (optionnel)"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="modeAbsenceActif",
            field=models.BooleanField(default=False, verbose_name="Mode absence actif"),
        ),
    ]
