# Generated by Django 5.2.10 on 2026-07-15 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_client_absencejusquau_client_modeabsenceactif"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contenu", models.TextField()),
                ("dateCreation", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_internes",
                        to="accounts.client",
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes_redigees",
                        to="accounts.technicien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note interne client",
                "verbose_name_plural": "Notes internes client",
                "ordering": ["-dateCreation"],
            },
        ),
    ]
