# Generated by Django 6.0.6 on 2026-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_noteclient"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
