# Generated by Django 6.0.6 on 2026-07-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_utilisateur_password_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="cle_api_ia_personnelle",
            field=models.CharField(
                blank=True,
                help_text="Si renseignée, utilisée à la place de la clé partagée du projet pour l'assistant IA.",
                max_length=200,
                null=True,
                verbose_name="Clé API IA personnelle (optionnel)",
            ),
        ),
    ]
