# Generated by Django 5.2.10 on 2026-07-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_client_cle_api_ia_personnelle"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="modele_api_ia_personnelle",
            field=models.CharField(
                blank=True,
                help_text="Requis si une URL personnalisée est renseignée ; sinon remplace le modèle par défaut du fournisseur détecté.",
                max_length=100,
                null=True,
                verbose_name="Nom du modèle IA personnalisé (optionnel)",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="url_api_ia_personnelle",
            field=models.CharField(
                blank=True,
                help_text="Endpoint compatible OpenAI (chat/completions) à utiliser à la place d'un fournisseur reconnu automatiquement.",
                max_length=300,
                null=True,
                verbose_name="URL de l'endpoint IA personnalisé (optionnel)",
            ),
        ),
    ]
