# Generated by Django 6.0.6 on 2026-10-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_client_modele_api_ia_personnelle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="cle_api_ia_personnelle",
        ),
        migrations.RemoveField(
            model_name="client",
            name="modele_api_ia_personnelle",
        ),
        migrations.RemoveField(
            model_name="client",
            name="url_api_ia_personnelle",
        ),
    ]
