# Generated by Django 6.0.6 on 2026-06-10 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispositif",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("apiKeyDevice", models.CharField(max_length=255, unique=True)),
                (
                    "firmwareVersion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("estConnecté", models.BooleanField(default=False)),
                ("adresseIP", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispositifs",
                        to="accounts.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Capteur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("type", models.CharField(default="Courant", max_length=100)),
                (
                    "valeurMax",
                    models.DecimalField(
                        decimal_places=2, default=2000.0, max_digits=10
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "coeffCalibration",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=6),
                ),
                ("derniereLecture", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capteurs",
                        to="accounts.client",
                    ),
                ),
                (
                    "dispositif",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capteurs",
                        to="sensors.dispositif",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MesureEnergie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "puissance",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Puissance (W)"
                    ),
                ),
                (
                    "courant",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Courant (A)"
                    ),
                ),
                (
                    "energie",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Énergie (kWh)"
                    ),
                ),
                (
                    "tension_V",
                    models.DecimalField(
                        decimal_places=1,
                        default=220.0,
                        max_digits=5,
                        verbose_name="Tension (V)",
                    ),
                ),
                (
                    "facteur_puissance",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.9,
                        max_digits=4,
                        verbose_name="Facteur de puissance",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "capteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesures",
                        to="sensors.capteur",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["capteur", "timestamp"],
                        name="sensors_mes_capteur_1716ef_idx",
                    )
                ],
            },
        ),
    ]
