# Generated by Django 6.0.6 on 2026-06-10 22:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_administrateur"),
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "typeIntervention",
                    models.CharField(
                        choices=[
                            ("INSTALLATION", "Installation"),
                            ("CALIBRATION", "Calibration"),
                            ("PANNE", "Déclaration de panne"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="MAINTENANCE",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("dateIntervention", models.DateTimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=50,
                    ),
                ),
                ("résultat", models.TextField(blank=True, null=True)),
                (
                    "capteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions",
                        to="sensors.capteur",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="accounts.client",
                    ),
                ),
                (
                    "dispositif",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions",
                        to="sensors.dispositif",
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="accounts.technicien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention",
                "verbose_name_plural": "Interventions",
                "ordering": ["-dateIntervention"],
            },
        ),
        migrations.CreateModel(
            name="RapportIntervention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contenu", models.TextField()),
                ("conclusion", models.TextField(blank=True, null=True)),
                ("dateGénération", models.DateTimeField(auto_now_add=True)),
                ("estValidé", models.BooleanField(default=False)),
                (
                    "intervention",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapport",
                        to="sensors.intervention",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport d'intervention",
                "verbose_name_plural": "Rapports d'intervention",
                "ordering": ["-dateGénération"],
            },
        ),
    ]
