# Generated by Django 6.0.6 on 2026-06-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_intervention_rapportintervention"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispositif",
            name="numeroSerie",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Numéro de série"
            ),
        ),
    ]
