# Generated by Django 5.2.10 on 2026-07-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0005_dispositif_nom_adresse"),
    ]

    operations = [
        migrations.AddField(
            model_name="capteur",
            name="etatCourant",
            field=models.CharField(
                choices=[("ON", "Allumé"), ("OFF", "Éteint")],
                default="OFF",
                max_length=3,
            ),
        ),
    ]
