# Generated by Django 5.2.10 on 2026-07-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0006_capteur_etatcourant"),
    ]

    operations = [
        migrations.AddField(
            model_name="capteur",
            name="cptOffConsecutifs",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
