# Generated by Django 5.2.10 on 2026-07-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0007_capteur_cptoffconsecutifs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="typeIntervention",
            field=models.CharField(
                choices=[
                    ("INSTALLATION", "Installation"),
                    ("CALIBRATION", "Calibration"),
                    ("PANNE", "Déclaration de panne"),
                    ("MAINTENANCE", "Maintenance"),
                    ("DIAGNOSTIC", "Diagnostic & Audits"),
                ],
                default="MAINTENANCE",
                max_length=50,
            ),
        ),
    ]
