# Generated by Django 5.2.10 on 2026-07-13 22:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0008_alter_intervention_typeintervention"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rapportintervention",
            name="conclusion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rapportintervention",
            name="contenu",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
