# Generated by Django 5.2.10 on 2026-07-15 02:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_utilisateur_is_2fa_enabled_and_more"),
        ("sensors", "0009_alter_rapportintervention_conclusion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actionType",
                    models.CharField(
                        choices=[
                            ("CALIBRATION_AUTO", "Calibration automatique"),
                            (
                                "CALIBRATION_MANUELLE",
                                "Modification directe du coefficient",
                            ),
                            ("EDITION_CAPTEUR", "Modification d’un capteur"),
                            ("REGENERATION_CLE", "Régénération de la clé API"),
                            ("ASSIGNATION_CAPTEUR", "Assignation d’un capteur"),
                            ("CREATION_CLIENT", "Création d’un compte client"),
                            ("EDITION_CLIENT", "Modification d’un client"),
                            ("EDITION_ABONNEMENT", "Modification d’un abonnement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("dateAction", models.DateTimeField(auto_now_add=True)),
                (
                    "capteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_journal",
                        to="sensors.capteur",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_journal",
                        to="accounts.client",
                    ),
                ),
                (
                    "dispositif",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_journal",
                        to="sensors.dispositif",
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions_journal",
                        to="accounts.technicien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action journalisée",
                "verbose_name_plural": "Journal d'actions",
                "ordering": ["-dateAction"],
            },
        ),
    ]
