# Generated by Django 5.2.10 on 2026-07-15 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0010_journalaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JournalAction",
        ),
    ]
