# Generated by Django 6.0.6 on 2026-07-15 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0011_delete_journalaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="commentaireClient",
            field=models.TextField(
                blank=True, null=True, verbose_name="Commentaire client"
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="dateProgrammee",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date programmée"
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="dateRetourClient",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="interventionOrigine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suivis",
                to="sensors.intervention",
                verbose_name="Intervention d'origine (si signalement de persistance)",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="satisfactionClient",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Satisfaction client (1 à 5)",
            ),
        ),
    ]
