# Generated by Django 5.2.10 on 2026-07-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0012_intervention_commentaireclient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capteur",
            name="derniereCalibration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
