# Generated by Django 6.0.6 on 2026-06-10 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPASSEMENT_SEUIL", "Dépassement de seuil"),
                            ("CONSOMMATION_NOCTURNE", "Consommation nocturne fantôme"),
                            ("CREDIT_BAS", "Crédit bas"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("lue", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("emailEnvoyé", models.BooleanField(default=False)),
                (
                    "sévérité",
                    models.CharField(
                        choices=[
                            ("Critique", "Critique"),
                            ("Avertissement", "Avertissement"),
                            ("Info", "Info"),
                        ],
                        default="Avertissement",
                        max_length=50,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes",
                        to="accounts.client",
                    ),
                ),
                (
                    "mesure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertes",
                        to="sensors.mesureenergie",
                    ),
                ),
            ],
            options={
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="RegleDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "puissanceMax_W",
                    models.DecimalField(
                        decimal_places=2, default=2000.0, max_digits=10
                    ),
                ),
                ("surveilleNuit", models.BooleanField(default=False)),
                ("heureDébutNuit", models.TimeField(default="00:00:00")),
                ("heureFinNuit", models.TimeField(default="05:00:00")),
                (
                    "capteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regles",
                        to="sensors.capteur",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regles",
                        to="accounts.client",
                    ),
                ),
            ],
        ),
    ]
