# Generated by Django 5.2.10 on 2026-07-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="regledetection",
            name="nom",
            field=models.CharField(default="Configuration", max_length=80),
        ),
    ]
